
spring:
  application:
    name: cockroachdb
  datasource:
    url: jdbc:postgresql://bigleg-penguin-3249.7s5.aws-ap-south-1.cockroachlabs.cloud:26257/anirudhMovies?sslmode=verify-full&password=e52EVgiJG95zQzkNkR014A&user=anirudh
    username: anirudh
    password: e52EVgiJG95zQzkNkR014A
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
      database: anirudhMovies
      database-platform: org.hibernate.dialect.PostgreSQLDialect
